name: Тестирование

on:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        oscript_version: ['1.2.0']

    steps:
      - uses: actions/checkout@v2
      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.0
        with:
          version: ${{ matrix.oscript_version }}
      - name: Установка зависимостей
        run: |
          opm install opm
          opm install xml-parser@0.1.1 && opm install 1connector@2.1.3 && opm install 1bdd && opm install 1testrunner && opm install asserts && opm install fs
      - name: Авторизация в hub.docker
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Запуск CRS
        run: docker run --name crs-host -d -p "5000:80" otymko/crs-apache:8.3.12.1855
      - name: Тестирование
        run: opm run test